# Generated by Django 5.2.6 on 2025-12-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('ENP', 'En Progreso'), ('RES', 'Resuelta'), ('REC', 'Rechazada')], default='PEN', max_length=3)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('num_votos', models.IntegerField(default=0)),
                ('num_comentarios', models.IntegerField(default=0)),
            ],
        ),
    ]
