# Generated by Django 6.0 on 2026-02-13 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        ('distrito', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Queja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente'), ('ENP', 'En Progreso'), ('RES', 'Resuelta'), ('REC', 'Rechazada')], default='PEN', max_length=3)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='categoria.categoria')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='distrito.distrito')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['estado'], name='quejas_quej_estado_453e07_idx'), models.Index(fields=['autor'], name='quejas_quej_autor_i_c7eb52_idx'), models.Index(fields=['categoria'], name='quejas_quej_categor_f777a7_idx'), models.Index(fields=['distrito'], name='quejas_quej_distrit_dc4d1a_idx'), models.Index(fields=['-fecha_creacion'], name='quejas_quej_fecha_c_0e75e0_idx')],
            },
        ),
    ]
