# Generated by Django 6.0 on 2026-02-16 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_alter_categoria_options_alter_categoria_activo_and_more'),
        ('distrito', '0002_alter_distrito_options_alter_distrito_codigo_and_more'),
        ('quejas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queja',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Queja', 'verbose_name_plural': 'Quejas'},
        ),
        migrations.AlterField(
            model_name='queja',
            name='autor',
            field=models.ForeignKey(help_text='Usuario autor que creó la queja.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='queja',
            name='categoria',
            field=models.ForeignKey(help_text='Categoría a la que pertenece la queja.', on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='categoria.categoria'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='descripcion',
            field=models.TextField(help_text='Descripción detallada de la incidencia.'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='distrito',
            field=models.ForeignKey(help_text='Distrito asociado a la queja.', on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='distrito.distrito'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('ENP', 'En Progreso'), ('RES', 'Resuelta'), ('REC', 'Rechazada')], default='PEN', help_text='Estado actual de la queja (PEN/ENP/RES/REC).', max_length=3),
        ),
        migrations.AlterField(
            model_name='queja',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización.'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la queja.'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='id',
            field=models.AutoField(help_text='Identificador único de la queja.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='queja',
            name='titulo',
            field=models.CharField(help_text='Título breve y descriptivo de la queja (máx. 200 caracteres).', max_length=200),
        ),
        migrations.AlterField(
            model_name='queja',
            name='ubicacion',
            field=models.CharField(blank=True, help_text='Ubicación opcional relacionada con la queja.', max_length=255, null=True),
        ),
    ]
