# Generated by Django 6.0 on 2026-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='queja',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
