# Generated by Django 6.0 on 2026-02-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente'), ('ENP', 'En Progreso'), ('RES', 'Resuelta'), ('REC', 'Rechazada')], default='PEN'),
        ),
    ]
