# Generated by Django 6.0 on 2026-01-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('quejas', '0002_alter_queja_fecha_creacion_alter_queja_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='categoria.categoria'),
        ),
    ]
