# Generated by Django 6.0 on 2026-01-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('quejas', '0003_queja_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='categoria',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='categoria.categoria'),
            preserve_default=False,
        ),
    ]
