# Generated by Django 6.0 on 2026-01-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrito', '0001_initial'),
        ('quejas', '0004_alter_queja_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='distrito.distrito'),
        ),
    ]
