# Generated by Django 6.0 on 2026-01-08 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrito', '0001_initial'),
        ('quejas', '0005_queja_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='distrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quejas', to='distrito.distrito'),
            preserve_default=False,
        ),
    ]
