# Generated by Django 6.0 on 2026-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0006_alter_queja_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queja',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
