# Generated by Django 6.0 on 2026-01-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0007_alter_queja_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queja',
            name='num_votos',
        ),
    ]
