# Generated by Django 6.0 on 2026-01-09 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quejas', '0009_queja_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queja',
            name='num_comentarios',
        ),
    ]
