# Generated by Django 6.0 on 2026-03-20 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quejas', '0002_alter_queja_options_alter_queja_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(help_text='Texto completo de la respuesta oficial.')),
                ('nuevo_estado', models.CharField(blank=True, choices=[('PEN', 'Pendiente'), ('ENP', 'En Progreso'), ('RES', 'Resuelta'), ('REC', 'Rechazada')], help_text='Estado al que pasa la queja tras esta respuesta (opcional).', max_length=3, null=True)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('moderador', models.ForeignKey(help_text='Moderador que emitió la respuesta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas_moderadas', to=settings.AUTH_USER_MODEL)),
                ('queja', models.ForeignKey(help_text='Queja a la que responde el moderador.', on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='quejas.queja')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
                'ordering': ['-fecha_respuesta'],
                'indexes': [models.Index(fields=['queja'], name='respuesta_r_queja_i_7173a4_idx'), models.Index(fields=['-fecha_respuesta'], name='respuesta_r_fecha_r_36fd41_idx'), models.Index(fields=['nuevo_estado'], name='respuesta_r_nuevo_e_2260da_idx')],
            },
        ),
    ]
