# Generated by Django 6.0 on 2026-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['id'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterField(
            model_name='distrito',
            name='codigo',
            field=models.CharField(help_text='Código identificativo del distrito. Mínimo 2 caracteres. Se almacena en mayúsculas.', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='id',
            field=models.AutoField(help_text='Identificador único del distrito.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nombre',
            field=models.CharField(help_text='Nombre del distrito. Mínimo 3 caracteres.', max_length=100, unique=True),
        ),
    ]
