# Generated by Django 6.0 on 2026-02-13 12:52

import django.db.models.deletion
import imagen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to=imagen.models.media_upload_to)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['orden', 'fecha_creacion'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='imagen_imag_content_41f15a_idx')],
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id', 'orden'), name='unique_image_order_per_object')],
            },
        ),
    ]
