# Generated by Django 6.0 on 2026-02-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='orden',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
