# Generated by Django 6.0 on 2026-02-16 17:31

import django.db.models.deletion
import imagen.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('imagen', '0002_alter_imagen_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagen',
            options={'ordering': ['orden', 'fecha_creacion'], 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imágenes'},
        ),
        migrations.AlterField(
            model_name='imagen',
            name='content_type',
            field=models.ForeignKey(help_text="Tipo de contenido del objeto relacionado (p. ej., 'queja' o 'comentario'). Internamente apunta al modelo de la app correspondiente.", on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro.'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='id',
            field=models.BigAutoField(help_text='Identificador único de la imagen.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(help_text="Archivo de imagen. Se almacenará bajo la ruta generada dinámicamente por 'media_upload_to'.", upload_to=imagen.models.media_upload_to),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='object_id',
            field=models.PositiveIntegerField(help_text='Identificador del objeto relacionado al que pertenece esta imagen.'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='orden',
            field=models.PositiveIntegerField(default=None, help_text='Posición de orden dentro del conjunto de imágenes del objeto relacionado. Si no se indica, se asigna automáticamente al guardar.'),
        ),
    ]
