# Generated by Django 6.0 on 2026-03-27 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(help_text='Identificador único de la sugerencia.', primary_key=True, serialize=False)),
                ('titulo', models.CharField(help_text='Título breve de la sugerencia.', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción completa de la sugerencia.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación.')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Última actualización.')),
                ('autor', models.ForeignKey(help_text='Usuario que creó la sugerencia.', on_delete=django.db.models.deletion.CASCADE, related_name='sugerencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['autor'], name='suggestion__autor_i_7f0c9d_idx'), models.Index(fields=['-fecha_creacion'], name='suggestion__fecha_c_3cf85f_idx')],
            },
        ),
    ]
