# Generated by Django 6.0 on 2026-01-08 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quejas', '0005_queja_distrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('num_votos', models.IntegerField(default=0)),
                ('queja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='quejas.queja')),
            ],
        ),
    ]
