# Generated by Django 6.0 on 2026-02-16 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
        ('quejas', '0002_alter_queja_options_alter_queja_autor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor',
            field=models.ForeignKey(help_text='Usuario autor del comentario.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.TextField(help_text='Contenido textual del comentario.'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del comentario.'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='id',
            field=models.AutoField(help_text='Identificador único del comentario.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Comentario al que este responde. Permite crear hilos.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='comentario.comentario', verbose_name='Comentario padre'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='queja',
            field=models.ForeignKey(help_text='Queja a la que pertenece el comentario.', on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='quejas.queja'),
        ),
    ]
