# Generated by Django 6.0 on 2026-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='quejaOcoment',
            field=models.BooleanField(default=True),
        ),
    ]
