# Generated by Django 6.0 on 2026-01-08 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comentario_quejaocoment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='quejaOcoment',
        ),
    ]
