# Generated by Django 6.0 on 2026-01-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0003_remove_comentario_quejaocoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='depth',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='comentario.comentario', verbose_name='Comentario Padre'),
        ),
    ]
