# Generated by Django 6.0 on 2026-01-09 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0004_comentario_depth_comentario_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='depth',
        ),
    ]
