# Generated by Django 6.0 on 2026-02-13 12:52

import django.core.validators
import django.db.models.deletion
import perfil.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', max_length=1)),
                ('biografia', models.TextField(blank=True)),
                ('moderator', models.BooleanField(default=False)),
                ('telefono', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente empezando por +.', regex='^\\+?\\d{7,15}$')])),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to=perfil.models.avatar_path)),
            ],
            options={
                'indexes': [models.Index(fields=['moderator'], name='perfil_perf_moderat_310e6d_idx'), models.Index(fields=['genero'], name='perfil_perf_genero_992921_idx')],
            },
        ),
    ]
