# Generated by Django 6.0 on 2026-02-16 17:31

import django.core.validators
import django.db.models.deletion
import perfil.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='biografia',
            field=models.TextField(blank=True, help_text='Descripción o biografía breve del usuario.'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, help_text='Dirección postal o de contacto.', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última actualización del perfil.'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento del usuario.', null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Avatar o foto de perfil del usuario.', null=True, upload_to=perfil.models.avatar_path),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='M', help_text='Género del usuario.', max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='moderator',
            field=models.BooleanField(default=False, help_text='Indica si el usuario tiene rol de moderador.'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono de contacto en formato internacional (+NN...).', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente empezando por +.', regex='^\\+?\\d{7,15}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(help_text='Usuario propietario de este perfil.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
