# Generated by Django 6.0 on 2026-02-26 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfil_options_alter_perfil_biografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(help_text='Dirección postal o de contacto.', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', help_text='Género del usuario.', max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(help_text='Teléfono de contacto en formato internacional (+NN...).', max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente empezando por +.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
