# Generated by Django 6.0 on 2026-02-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0003_alter_perfil_direccion_alter_perfil_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(default="2003-11-20", help_text='Fecha de nacimiento del usuario.'),
            preserve_default=False,
        ),
    ]
