# Generated by Django 6.0 on 2026-02-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_perfil_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
