# Generated by Django 6.0 on 2026-02-12 11:30

import django.core.validators
import perfil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_remove_perfil_id_alter_perfil_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to=perfil.models.avatar_path),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 7 y 15 dígitos, opcionalmente empezando por +.', regex='^\\+?\\d{7,15}$')]),
        ),
    ]
