# Generated by Django 6.0 on 2026-02-12 11:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_alter_perfil_foto_perfil_alter_perfil_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['moderator'], name='perfil_perf_moderat_310e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='perfil',
            index=models.Index(fields=['genero'], name='perfil_perf_genero_992921_idx'),
        ),
    ]
