# Generated by Django 6.0 on 2026-02-16 17:31

import django.db.models.deletion
import video.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['orden', 'fecha_creacion'], 'verbose_name': 'Video', 'verbose_name_plural': 'Videos'},
        ),
        migrations.AlterField(
            model_name='video',
            name='content_type',
            field=models.ForeignKey(help_text='Modelo al que está asociado el video (p. ej., queja o comentario).', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='video',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='id',
            field=models.BigAutoField(help_text='Identificador único del video.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID del objeto concreto dentro del modelo asociado.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='orden',
            field=models.PositiveIntegerField(default=0, help_text='Posición del video dentro del objeto padre.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(help_text='Archivo de video subido (multipart/form-data).', upload_to=video.models.media_upload_to),
        ),
    ]
