# Generated by Django 6.0 on 2026-02-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si la categoría está activa y disponible para su uso.'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.TextField(help_text='Descripción breve que explica el propósito de la categoría.'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(help_text='Identificador único de la categoría.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text="Nombre visible de la categoría. Ejemplo: 'Transporte', 'Limpieza', etc.", max_length=100, unique=True),
        ),
    ]
