# Generated by Django 6.0 on 2026-02-11 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('megusta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='megusta',
            index=models.Index(fields=['content_type', 'object_id'], name='megusta_meg_content_8b31fa_idx'),
        ),
    ]
