# Generated by Django 6.0 on 2026-02-16 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('megusta', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='megusta',
            options={'verbose_name': 'Me Gusta', 'verbose_name_plural': 'Me Gustas'},
        ),
        migrations.AlterField(
            model_name='megusta',
            name='autor',
            field=models.ForeignKey(help_text="Usuario que dio el 'me gusta'.", on_delete=django.db.models.deletion.CASCADE, related_name='megustas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='megusta',
            name='content_type',
            field=models.ForeignKey(help_text='Modelo al que está asociado el Like (queja/comentario).', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='megusta',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text="Fecha en la que se realizó el 'me gusta'."),
        ),
        migrations.AlterField(
            model_name='megusta',
            name='id',
            field=models.AutoField(help_text='Identificador único del MeGusta.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='megusta',
            name='object_id',
            field=models.PositiveIntegerField(help_text='ID del objeto dentro del modelo asociado.'),
        ),
    ]
